In [ ]:
import pandas as pd
import sqlite3

In [ ]:
households = pd.read_excel(r"C:\Users\Norah\Downloads\undesa_pd_2022_hh-size-composition (2) (1).xlsx",sheet_name='Sheet1')
households = households.drop(columns=['Reference date (dd/mm/yyyy)'])
households = households.rename(columns={'Average household size (number of members)':'Values'})
households['Values'] = pd.to_numeric(households['Values'], errors='coerce')
households1 = households.pivot_table(index=['Country or area'],columns='Year',values='Values')

country = pd.read_excel("UNDP Country.xlsx")
households1 = country.merge(households1, on='Country or area', how='left')
households1 = households1.drop(columns='Country or area')

drop31 = households1.iloc[:, 0:2]

house1 = households1.iloc[:, 3:62] 

households1 = pd.concat([drop31, house1], axis=1)
households1

,Country,FIPS_CODE,1960,1962,1963,1964,1966,1968,1969,1970,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.3,NaN,NaN,NaN,NaN
2,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.420,NaN,NaN,NaN,NaN,NaN,4.94,NaN,NaN,NaN
3,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.82,NaN,NaN,NaN,NaN,NaN
4,Argentina,ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.95,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,"Venezuela, Bolivarian Republic",VEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,Viet Nam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.86,NaN,NaN,NaN,NaN,NaN,4.72,3.44,NaN
185,Yemen,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,Zambia,ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.240,5.13,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN
187,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.115,NaN,4.12,NaN,NaN,NaN,NaN,4.02,NaN,NaN

population

In [12]:
#connect to database
con = sqlite3.connect(r"c:\IFs\DATA\IFsHistSeries.db")
sql_query = """SELECT name FROM sqlite_master  
  WHERE type='table';"""

cursor = con.cursor()

cursor.execute(sql_query)

tbname = 'SeriesPopulation'

population = pd.read_sql_query(f"SELECT * FROM '{tbname}'", con)
population = population.drop(columns=['Earliest', 'MostRecent'])

#population.info()

popdrop = population.iloc[:, 0:2]
popdrop1 = population.iloc[:, 12:74] 
pop1 = pd.concat([popdrop, popdrop1], axis=1)

pop1

,Country,FIPS_CODE,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Afghanistan,AFG,9.0350,9.2141,9.4044,9.6045,9.8143,10.0360,10.2664,10.5060,...,30.5600,31.6227,32.7925,33.8318,34.7006,35.6889,36.7430,37.8561,39.0690,40.0004
1,Albania,ALB,1.6494,1.6988,1.7437,1.7913,1.8414,1.8943,1.9500,2.0085,...,2.9100,2.9076,2.9037,2.8986,2.8979,2.8982,2.8942,2.8850,2.8720,2.8496
2,Algeria,DZA,11.4249,11.6289,11.8008,11.9821,12.1798,12.3660,12.5901,12.8761,...,37.6462,38.4142,39.2050,40.0195,40.8507,41.6893,42.5050,43.2945,44.0421,44.7611
3,Angola,AGO,5.2317,5.3016,5.3543,5.4083,5.4642,5.5220,5.5814,5.6418,...,25.1774,26.1656,27.1608,28.1578,29.1831,30.2348,31.2972,32.3756,33.4511,34.5324
4,Argentina,ARG,20.3860,20.7263,21.0725,21.4217,21.7695,22.1126,22.4539,22.7991,...,42.1617,42.5825,43.0241,43.4770,43.9003,44.2889,44.6549,44.9735,45.1920,45.3123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,"Venezuela, Bolivarian Republic",VEN,8.1601,8.4559,8.7569,9.0640,9.3777,9.6978,10.0249,10.3585,...,29.5538,29.9122,30.2541,30.5740,30.7657,30.5653,29.8076,28.9381,28.4441,28.2378
184,Viet Nam,VNM,32.5319,33.4091,34.2886,35.2491,36.2016,37.1297,38.0248,38.8951,...,89.5104,90.5731,91.6796,92.8233,94.0001,95.1770,96.2373,97.1738,98.0792,98.9351
185,Yemen,YEM,5.5323,5.6552,5.7822,5.9111,6.0480,6.1956,6.3515,6.5164,...,28.4336,29.3130,30.2263,31.1594,32.1090,33.0909,34.0852,35.1114,36.1349,37.1402
186,Zambia,ZMB,3.1537,3.2541,3.3581,3.4659,3.5770,3.6921,3.8120,3.9363,...,14.9136,15.3990,15.8953,16.3991,16.9144,17.4413,17.9736,18.5138,19.0594,19.6036
187,Zimbabwe,ZWE,3.8094,3.9304,4.0560,4.1859,4.3200,4.4585,4.6012,4.7483,...,13.8179,14.0138,14.2074,14.3990,14.6003,14.8125,15.0345,15.2714,15.5269,15.7972

In [ ]:
households1.to_excel("households1.xlsx", index=False)
pop1.to_excel("population1.xlsx", index=False)

#divided pop/households manually

In [ ]:
numhouse = pd.read_excel("population1.xlsx",sheet_name='house')
numhouse

year_columns = [col for col in numhouse.columns if str(col).isdigit()]
numhouse['Earliest'] = numhouse[year_columns].bfill(axis=1).iloc[:, 0]
numhouse['MostRecent'] = numhouse[year_columns].ffill(axis=1).iloc[:, -1]
numhouse[year_columns + ['Earliest', 'MostRecent']] = numhous
e[year_columns + ['Earliest', 'MostRecent']].round(4)

numhouse

,Country,FIPS_CODE,1960,1962,1963,1964,1966,1968,1969,1970,...,2014,2015,2016,2017,2018,2019,2020,2021,Earliest,MostRecent
0,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.1622,3.3432
1,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.8799,NaN,NaN,NaN,NaN,0.8535,0.8799
2,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.1011,NaN,NaN,NaN,6.5480,8.1011
3,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.4285,NaN,NaN,NaN,NaN,NaN,3.1915,5.4285
4,Argentina,ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0315,...,NaN,NaN,NaN,NaN,NaN,14.8815,NaN,NaN,6.0315,14.8815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,"Venezuela, Bolivarian Republic",VEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0299,5.4506
184,Viet Nam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,19.9153,27.6677,NaN,12.5201,27.6677
185,Yemen,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2406,3.7649
186,Zambia,ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.2798,NaN,NaN,NaN,1.2293,3.2798
187,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.2999,NaN,NaN,NaN,NaN,3.6319,NaN,NaN,2.4427,3.6319

In [22]:
conn = sqlite3.connect(r"C:\IFs\RUNFILES\IFsDataImport - Copy (5) - Copy - Copy.db")
cursor = conn.cursor()

table_name = 'SeriesNumberofHouseholds'
columns_sql = ['Country VARCHAR(255)', 'FIPS_CODE VARCHAR(255)']
columns_sql += [f'"{col}" DOUBLE(53)' for col in year_columns + ['Earliest', 'MostRecent']]
create_table_sql = f"CREATE TABLE '{table_name}' ({', '.join(columns_sql)})"

numhouse.to_sql(table_name, conn, if_exists='replace', index=False)

conn.commit()
conn.close()